### ISSUE TITLE
Emails are converted incorrectly

### ISSUE THREAD

**Issue by SGrishin** [markdown-it/markdown-it-mark#2]
Emails are converted incorrectly.

For example:

"example==@example.example=="

converted to

"example==@example.example=="

Could you fix it please?

**Comment by puzrin** [comment]
This package is not about emails. It's a sample how to create something, following generic emphasis approach from CM spec. If you need different logic, you should create a fork.

**Comment by SGrishin** [comment]
Maybe I did not quite put it right. I mean it's bug because "==@example==" converted to <p><mark>@example</mark></p> but if any symbol pasted  before ("e==@example==") then it converte to "e==@example==".  Also "e == example ==" is converted to <p>e<mark>example</ mark></ p>.

I'm also not sure that this is a markdown-it-mark bug, not a markdown-it. It would be great if you could clarify this.

Thanks.

**Comment by puzrin** [comment]
That's notmal. See CM spec, how emphasis (** and __) works. That's not a bug.

**Comment by SGrishin** [comment]
Thanks.
