### ISSUE TITLE
Wrong highlight for multiline text

### ISSUE THREAD

**Issue by ogonkov** [markdown-it/markdown-it-mark#4]
This text is rendered with multiline `<mark>`

```
exposed-java-time==0.38.2
exposed-money==0.38.2
```

Produced html

```html
<p>exposed-java-time<mark>0.38.2<br>
exposed-money</mark>0.38.2</p>
```

I was hoping to see something like

```html
<p>exposed-java-time==0.38.2<br>
exposed-money==0.38.2</p>
```

Am i wrong?

**Comment by puzrin** [comment]
I guess you could use escaping (`\==`). It's impossible to always assume automatically what users can wish.

In general, you can take a look at emphasis / strikethrough rules and tweak your custom one as you prefer.
