### ISSUE TITLE
Support auto close mark at the end of the paragraph

### ISSUE THREAD

**Issue by ZhongxuYang** [markdown-it/markdown-it-mark#5]
Hello, I used this plugin when migrating Obsidian's content to a renderer implemented using markdown-it. Thank you for your contribution.

But I encountered a problem, I'm not sure if it's a reasonable requirement:
In the Obsidian, it is allowed to only have the starting ==, and the mark will end at the end of the paragraph (that is, if the user does not enter an ending label in this paragraph, it will automatically end at the end of the paragraph).

like this:
```md
This is a test text. ==Starting from here, it will be highlighted.

This is the second paragraph that won't be highlighted.
```

**Comment by puzrin** [comment]
Inline markup can not be spread to multiple paragraphs. See CM spec.
